package com.juancarlos.apptriplel.models

import java.util.*
//Determinante, Cadena, Sucursal, Latitud, Longitud
data class TiendasUsuario(
    var Activo : Int,
    var Altitud : Int,
    var AreaFlexFrentes : String,
    var ArietesFrentes : String,
    var Bateria : String,
    var CP : String,
    var CabeceraFrentes : String,
    var Cadena:  String,
    var CadenaFecha : String,
    var CajasFrentes : String,
    var Calle : String,
    var CantAnaquel : String,
    var CantBodega : String,
    var CantFrentesEnFrio : String,
    var Colonia: String,
    var ComentarioAnaquel : String,
    var ComentarioBodega : String,
    var ComentarioExhAdic : String,
    var ComentarioFrentesEnFrio : String,
    var DeterminanteGSP : String,
    var DeterminanteTienda : String,
    var Direccion: String,
    var Estatus : String,
    var Facturacion : String,
    var Fecha: String,
    var FechaSync : Int,
    var ForwayFrentes : String,
    var Id : Int,
    var IdCadena : Int,
    var IdCanal : Int,
    var IdCategoria : Int,
    var IdCiudad : String,
    var IdEstado : String,
    var IdFormato : String,
    var IdFoto : String,
    var IdGrupo : Int,
    var IdMunicipio : String,
    var IdPais : String,
    var IdProyecto : String,
    var IdUsuario : String,
    var IdVisita_Server : Int,
    var IsAreaFlex : String,
    var IsAriete : String,
    var IsBunkers : String,
    var IsC1 : String,
    var IsC2 : String,
    var IsC3 : String,
    var IsC4 : String,
    var IsCabecera : String,
    var IsCajas : String,
    var IsExhibidores : String,
    var IsForway : String,
    var IsIsla : String,
    var IsMaterialPOP : String,
    var IsOtro : String,
    var IsTiras : String,
    var IslasFrentes : String,
    var Latitud: Float,
    var Longitud: Float,
    var Manos : String,
    var ManosC1 : String,
    var ManosC2 : String,
    var ManosC3 : String,
    var ManosC4 : String,
    var ManosFrentesEnFrio : String,
    var MatPOPCartulina : String,
    var MatPOPCenefas : String,
    var MatPOPColgantes : String,
    var MatPOPCorbata : String,
    var MatPOPDanglers : String,
    var MatPOPFaldon : String,
    var MatPOPFlash : String,
    var MatPOPFolleto : String,
    var MatPOPOtros : String,
    var MatPOPPreciador : String,
    var MatPOPStoppers : String,
    var MatPOPTapete : String,
    var MatPOPTira : String,
    var Nielsen : String,
    var NuevoPunto : String,
    var Numero : String,
    var Ojo : String,
    var OjoC1 : String,
    var OjoC2 : String,
    var OjoC3 : String,
    var OjoC4 : String,
    var OjoFrentesEnFrio : String,
    var OtrosFrentes : String,
    var Precio : String,
    var PrecioFrentesEnFrio : String,
    var RangoGPS : String,
    var SKU : String,
    var Statussync : Int,
    var Sucursal: String,
    var Suelo : String,
    var SueloC1 : String,
    var SueloC2 : String,
    var SueloC3 : String,
    var SueloC4 : String,
    var SueloFrentesEnFrio : String,
    var TarimasBodega : String,
    var Techo : String,
    var TechoC1 : String,
    var TechoC2 : String,
    var TechoC3 : String,
    var TechoC4 : String,
    var TechoFrentesEnFrio : String,
    var Telefonos : String,
    var TirasFrentes : String,
    var TramosAnaquel : String,
    var TramosFrentesEnFrio : String,
    var Ufechadescarga : String,
    var agrupador: String,
    var determinante : Int,
    var nvarombreComercial:String
)